### ISSUE TITLE
Create scastie wireframes

### ISSUE THREAD

**Issue by dominv** [47deg/scastie#2]
Create scastie designs

**Comment by dominv** [comment]
The wireframes are currently in validation by the client

**Comment by Antoniojimenez47** [comment]
Hi! @jorgegalindocruces @dominv and @israelperezglez 
I have updated the Scastie wireframe in Invision.
Can you check it? Please
https://projects.invisionapp.com/d/main#/projects/prototypes/10429929

Thanks!

**Comment by Antoniojimenez47** [comment]
Hi! @jorgegalindocruces @dominv and @israelperezglez 

I updated the changes on the Wireframe of Scastie, in the platform of Invision.
https://projects.invisionapp.com/d/main#/projects/prototypes/10429929

Can you check it? Please

Thanks!

**Comment by israelperezglez** [comment]
Look good for me ;)
