### ISSUE TITLE
Create scastie logo

### ISSUE THREAD

**Issue by anamariamv** [47deg/scastie#4]
We should create a scastie logo with the following features.

The brand has to have the new color palette created for Scala Lang and has to have the technological style as Scala Center and Scala Lang

**Comment by jorgegalindocruces** [comment]
Please, we should try add proper description. Thanks!

**Comment by Antoniojimenez47** [comment]
Hi! @israelperezglez @jorgegalindocruces 

I added the Scastie brand proposals.
https://projects.invisionapp.com/d/main#/projects/prototypes/10429929

Can you check it? Please.
Thanks!
